FROM node:22-slim AS builder
WORKDIR /app
COPY package.json ./
COPY .npmrc ./
RUN npm install --legacy-peer-deps
COPY . .
RUN npm run build -- --configuration development

FROM nginx:alpine
COPY --from=builder /app/dist/daf360-payroll/browser /usr/share/nginx/html
COPY nginx.dev.conf /etc/nginx/conf.d/default.conf
EXPOSE 4205
